### ISSUE TITLE
Fix tests not passing in last master merge.

### ISSUE THREAD

**Issue by psorianom** [etalab-ia/piaf-ml#115]
Right now, the tests are not working for the last merge.

**Comment by psorianom** [comment]
@AbdenourCh thanks for your PR! Just be careful with not merging your own PRs (which happened this time via the commands you used). Also, can you change your git user name because right now we see "Admin" as the user name that pushed. See below: 
![image](https://user-images.githubusercontent.com/1085210/123103055-ef6a2c00-d435-11eb-8f29-d053194975b9.png)

**Comment by AbdenourCh** [comment]
@psorianom  Thanks for pointing out the problem with the username alongside the solution. As for the failing tests problem, I fixed it in PR  #114.

**Comment by psorianom** [comment]
cool, thanks!
