### ISSUE TITLE
Test de charge FAILED : where could this come from ?

### ISSUE THREAD

**Issue by MichaelBitard** [etalab-ia/piaf-ml#116]
- [ ] RAM trop faible ? => probably not because the docker logs show answers are handled, but some in more than 30sec
- [x] timeout NGINX ?
- [x] timeout FAST API / gunicorn (timeout 180) => a probably not
- [ ] timeout ES ?
- [ ] timeout Netlify ? => probaly not
- [ ] timeout DNS etalab ? => probaly not
- [ ] chrome (browser) [stackoverflow](https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools)

Sounds like a timout of 10seconds. In the logs I see some calls answering in more that 10 seconds, so it could be linked to NGINX of FASTAPI

link https://github.com/deepset-ai/haystack/issues/1228

**Comment by MichaelBitard** [comment]
First hint: the RequestLimiter in haystack seems to responds 503 errors with "The server is busy processing requests."

Step to reproduce: 
I launched 4 parallel curl with tmux: https://asciinema.org/a/Ov6d1NmzTzv6tPRXcKInm6pcS

**Comment by guillim** [comment]
created this issue in Haystack : https://github.com/deepset-ai/haystack/issues/1229

**Comment by MichaelBitard** [comment]
you created this one too: https://github.com/deepset-ai/haystack/issues/1228
