### ISSUE TITLE
Missing parenthesis

### ISSUE THREAD

**Issue by psorianom** [etalab-ia/piaf-ml#142]
@guillaumecherel  It seems here that you are not accomplishing what you wanted ? If I do not have `ELASTICSEARCH_PORT` defined, it will try to cast `None` as `int`, which will fail. https://github.com/etalab-ia/piaf-ml/blob/e8e67d2e1e18281ef3e3ee4e6a8ba0924746c157/src/evaluation/retriever_reader/retriever_reader_eval_squad.py#L512

**Comment by guillaumecherel** [comment]
Indeed, thanks for this @psorianom.

Fixed in #143
