### ISSUE TITLE
Add user feedback in PIAF

### ISSUE THREAD

**Issue by Rob192** [etalab-ia/piaf-ml#32]
This is an improvement that aims at using the user feedback in PIAF. There are two aspects in this feature : 
1. Design the graphical interface to collect such feedback in Piaf Agent or Piaf Bot (see related : https://github.com/deepset-ai/haystack/issues/864)
2. Use these feedback for either 
a. Finer performance evaluation 
b. Improvement of the performances : via a finetuning of the `Reader` or question matching pipeline similar to the `TitleQAPipeline`

**Comment by guillim** [comment]
Closing this. seems good to me now
