### ISSUE TITLE
Add a non-regression test on our evaluation script

### ISSUE THREAD

**Issue by Rob192** [etalab-ia/piaf-ml#64]
Currently, when we develop our evaluation scripts, the good practice is to add a new test with `pytest` in the `/test` folder. However, this test is performed on specific test knowledge base such as `tiny.json` that are small on purpose. We should also add a non regression test on larger dataset such as fsquad.json in order to verify that the behavior is still the same at some specific parameters.

**Comment by guillim** [comment]
Almost done. Last check to do with DILA dataset /clients/dila/knowledge_base/squad.json

**Comment by guillim** [comment]
Score are Ok @guillaumecherel
